apiVersion: apps/v1
kind: Deployment
metadata:
  name: h8st-static-website
spec: 
  selector: 
    matchLabels:
      app: static-website
  replicas: 1
  template:
    metadata:
      labels:
        app: static-website
    spec: 
      containers: 
      - name: static-website
        image: httpd:2.4
        volumeMounts:
          - mountPath: /usr/local/apache2/htdocs/index.html
            subPath: index.html
            name: cfgmap
        ports:
        - containerPort: 80
      volumes:
        - name: cfgmap
          configMap:
            name: config

---
apiVersion: v1
kind: Service
metadata:
  name: h8st-static-website
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: static-website

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: h8st-localhost
spec:
  ingressClassName: nginx
  rules:
  - host: my.dummy.domain
    http:
      paths:
      - backend:
          service:
            name: h8st-static-website
            port:
              number: 80
        path: /
        pathType: Prefix
